#!/usr/bin/env bash
# vim: ts=4:sw=4:noet:ai

# Check for CA_ROOT variable
if [ -z "$CA_ROOT" ]
then
    echo "Please source the CA shell environment from the \"env.sh\" file."
    exit 1
fi

CONFNAME=$1
DNSNAME=$2

if [ -z "$CONFNAME" ]; then
	echo "ERROR: Configuration file not provided."
	exit 1
fi

if [ -z "$DNSNAME" ]; then
	DNSNAME="$CONFNAME"
fi

CONFFILE="$CA_ROOT/configs/$CONFNAME.conf"

shift
shift

# Compose main sections
cat > $CONFFILE <<EOF
[ req ]
distinguished_name = req_dn
req_extensions = req_exts
prompt = no

[ req_dn ]
CN                 = $DNSNAME
#OU                 = Organizational Unit Name
#O                  = Optional organization name
#L                  = Optional city name
#ST                 = State or Province
#C                  = Optional country code, e.g. PL

[ req_exts ]
EOF

# Create default recommended SAN
SANS="subjectAltName = DNS:$DNSNAME"

SAN=$1

# Process additional parameters to add more SANs
while [ ! -z $SAN ]
do
	# Check if the SAN is an IP address
	if echo $SAN | grep -q -E '^([[:digit:]]{1,3}\.){3}[[:digit:]]{1,3}$'
	then
		SANS=$SANS", IP:$SAN"
	else
		SANS=$SANS", DNS:$SAN"
	fi
	shift
	SAN=$1
done

echo $SANS >> $CONFFILE

echo "Configuration file has been created: \"$CONFFILE\"."

echo "============================================================"
cat $CONFFILE
echo "============================================================"

echo "Edit it to change certificate attributes."
