#!/usr/bin/env bash
# vim: ts=4:sw=4:noet:ai

# Check for CA_ROOT variable
if [ -z "$CA_ROOT" ]
then
    echo "Please source the CA shell environment from the \"env.sh\" file."
    exit 1
fi

if [ ! -f $CA_ROOT/dh.pem ]
then
    openssl dhparam -out "$CA_ROOT/dh.pem" 2048
else
    echo "The DH param file already exists."
    exit 1
fi

