#!/usr/bin/env bash
# vim: ts=4:sw=4:noet:ai

# Check for CA_ROOT variable
if [ -z "$CA_ROOT" ]
then
    echo "Please source the CA shell environment from the \"env.sh\" file."
    exit 1
fi

if ! $CA_SCRIPTS/sk-make-conf $*
then
    exit 1
fi

if ! $CA_SCRIPTS/sk-make-req $1
then
    exit 1
fi

if ! $CA_SCRIPTS/sk-sign-req $1
then
    exit 1
fi
